---
image_pull_secrets:
- DOCKER_REGISTRY_AUTHENTICATION_JSON
kind: pipeline
name: Publishing pipeline
steps:
- commands:
  - 'blaze --jsonnet-var ''{ playwright: { installDeps: false } }'' run cv:publish'
  - blaze run cv:deploy
  environment:
    DOCKER_REGISTRY_PASSWORD:
      from_secret: DOCKER_REGISTRY_PASSWORD
    DOCKER_REGISTRY_USERNAME:
      from_secret: DOCKER_REGISTRY_USERNAME
  image: registry.rnzaou.me/ci:latest
  name: publish
  pull: always
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
trigger:
  branch:
  - master
  event:
  - custom
  - push
type: docker
volumes:
- host:
    path: /run/user/1002/docker.sock
  name: docker-socket
---
kind: signature
hmac: 3977ea38e7235f970abe88f836da5bcf36f1c2171380c3fa10938885ee9c0a2d

...
