---
image_pull_secrets:
- DOCKER_REGISTRY_AUTHENTICATION_JSON
kind: pipeline
name: Publishing pipeline
steps:
- commands:
  - blaze run cv:publish
  - blaze run cv:deploy
  environment:
    DOCKER_REGISTRY_PASSWORD:
      from_secret: DOCKER_REGISTRY_PASSWORD
    DOCKER_REGISTRY_USERNAME:
      from_secret: DOCKER_REGISTRY_USERNAME
  image: registry.rnzaou.me/ci:latest
  name: publish
  pull: always
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
trigger:
  branch:
  - master
  event:
  - custom
  - push
type: docker
volumes:
- host:
    path: /run/user/1002/docker.sock
  name: docker-socket
---
kind: signature
hmac: 10e308af512d24e2211d4f47a61224dc13ef87d525629c91b44a8c2f0058e615

...
