services:
  cv:
    image: registry.rnzaou.me/cv:latest
    container_name: cv
    restart: always
    expose:
      - 80/tcp
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
