// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_locale_middleware from './routes/[locale]/_middleware.tsx'
import * as $_locale_index from './routes/[locale]/index.tsx'
import * as $_app from './routes/_app.tsx'
import * as $_middleware from './routes/_middleware.tsx'
import * as $index from './routes/index.tsx'
import * as $ContactInfo from './islands/ContactInfo.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/[locale]/_middleware.tsx': $_locale_middleware,
    './routes/[locale]/index.tsx': $_locale_index,
    './routes/_app.tsx': $_app,
    './routes/_middleware.tsx': $_middleware,
    './routes/index.tsx': $index,
  },
  islands: {
    './islands/ContactInfo.tsx': $ContactInfo,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
